import { 
  Home, 
  Send, 
  Code, 
  ChevronRight, 
  Bell, 
  CircleUser, 
  Sparkles, 
  Zap, 
  CircleCheck, 
  Settings, 
  Calendar, 
  Info, 
  CircleHelp,
  Flame,
  Search,
  BookOpen,
  GraduationCap,
  Activity,
  Trophy,
  Files,
  Clock,
  ChevronLeft,
  Mail,
  Key,
  X,
  Diamond,
  Star,
  Users,
  ShieldCheck,
  FileText,
  Download,
  Compass,
  Sun,
  BatteryWarning,
  FlaskConical,
  PenTool,
  Library,
  Briefcase,
  Plus,
  LayoutGrid,
  Medal,
  User,
  Camera,
  Snowflake,
  Scan,
  Album,
  Type,
  ZapOff,
  Gift,
  Check,
  XCircle,
  Lightbulb,
  Wand2,
  Share2,
  Upload,
  Timer,
  Leaf,
  Rocket,
  List,
  RotateCcw,
  Pencil,
  ArrowUpCircle,
  TriangleAlert,
  RefreshCcw,
  Eye,
  EyeClosed,
  NotepadText,
  HelpCircle,
  LogOut,
  Trash2,
  Cpu,
  CreditCard,
  ThumbsUp,
  ThumbsDown,
  ArrowRight,
  PlusCircle,
  Shapes,
  Apple
} from 'lucide-react-native';
import React from 'react';
import { type StyleProp, type ViewStyle } from 'react-native';

// Mapping SF Symbol names to Lucide icons
export const MAPPING = {
  'house.fill': Home,
  'apple.logo': Apple,
  'paperplane.fill': Send,
  'chevron.left.forwardslash.chevron.right': Code,
  'chevron.right': ChevronRight,
  'bell.fill': Bell,
  'person.circle.fill': CircleUser,
  'sparkles': Sparkles,
  'bolt.fill': Zap,
  'checkmark.circle.fill': CircleCheck,
  'gearshape.fill': Settings,
  'calendar': Calendar,
  'info.circle.fill': Info,
  'questionmark.circle.fill': CircleHelp,
  'flame.fill': Flame,
  'magnifyingglass': Search,
  'book.fill': BookOpen,
  'graduationcap.fill': GraduationCap,
  'activity': Activity,
  'trophy.fill': Trophy,
  'doc.on.doc.fill': Files,
  'clock.fill': Clock,
  'chevron.left': ChevronLeft,
  'envelope.fill': Mail,
  'key.fill': Key,
  'xmark': X,
  'diamond.fill': Diamond,
  'star.fill': Star,
  'person.2.fill': Users,
  'shield.check.fill': ShieldCheck,
  'doc.text.fill': FileText,
  'square.and.arrow.down.fill': Download,
  'compass.drawing': Compass,
  'sun.max.fill': Sun,
  'battery.100.bolt': BatteryWarning,
  'flask.fill': FlaskConical,
  'hammer.fill': PenTool,
  'books.vertical.fill': Library,
  'briefcase.fill': Briefcase,
  'plus': Plus,
  'square.grid.2x2.fill': LayoutGrid,
  'medal.fill': Medal,
  'person.fill': User,
  'camera.fill': Camera,
  'snowflake': Snowflake,
  'viewfinder': Scan,
  'photo.on.rectangle': Album,
  'textformat': Type,
  'bolt.slash.fill': ZapOff,
  'gift.fill': Gift,
  'checkmark': Check,
  'xmark.circle.fill': XCircle,
  'lightbulb.fill': Lightbulb,
  'wand.and.stars': Wand2,
  'square.and.arrow.up': Share2,
  'square.and.arrow.up.on.square.fill': Upload,
  'timer': Timer,
  'leaf.fill': Leaf,
  'rocket.fill': Rocket,
  'list.bullet': List,
  'arrow.counterclockwise': RotateCcw,
  'pencil': Pencil,
  'arrow.up.circle.fill': ArrowUpCircle,
  'exclamationmark.triangle.fill': TriangleAlert,
  'arrow.clockwise': RefreshCcw,
  'eye.fill': Eye,
  'eye.slash.fill': EyeClosed,
  'notepad': NotepadText,
  'questionmark.circle': HelpCircle,
  'arrow.right.to.line': LogOut,
  'trash.fill': Trash2,
  'sparkles.rectangle.stack.fill': Shapes,
  'cpu': Cpu,
  'creditcard.fill': CreditCard,
  'checkmark.shield.fill': ShieldCheck,
  'list.bullet.indent': List,
  'doc.on.doc': Files,
  'hand.thumbsup': ThumbsUp,
  'hand.thumbsdown': ThumbsDown,
  'arrow.right': ArrowRight,
  'camera': Camera,
  'plus.circle.fill': PlusCircle,
} as const;

export type IconSymbolName = keyof typeof MAPPING;

/**
 * An icon component that uses Lucide icons for a consistent look on Android & Web.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
  strokeWidth = 2.5
}: {
  name: IconSymbolName;
  size?: number;
  color: string;
  style?: StyleProp<ViewStyle>;
  strokeWidth?: number;
}) {
  const IconComponent = MAPPING[name];
  
  if (!IconComponent) return null;

  return (
    <IconComponent 
      width={size} 
      height={size} 
      color={color} 
      strokeWidth={strokeWidth} 
      style={style as any} 
    />
  );
}
