import { Text } from '@/components/ui/Text';
import { View, StyleSheet, Image, ViewStyle, TextStyle, ImageStyle } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { GoogleIcon, AppleIcon } from '@/components/ui/BrandIcons';


interface QuizShareCardProps {
    topic: string;
    percentage: number;
    strength?: string;
    focusArea?: string;
}

const GRADIENTS = [
    ['#4f46e5', '#3b82f6', '#2563eb'], // Indigo/Blue (Default)
    ['#8b5cf6', '#a855f7', '#d946ef'], // Purple/Pink
    ['#0ea5e9', '#2dd4bf', '#14b8a6'], // Sky/Teal
    ['#334155', '#475569', '#1e293b'], // Slate/Dark
    ['#f59e0b', '#ef4444', '#b91c1c'], // Amber/Red
];

export const QuizShareCard = ({ topic, percentage, strength, focusArea }: QuizShareCardProps) => {
    // Select a gradient based on the topic name hash to keep it "stable" for a topic but varying between topics
    const topicHash = topic.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const gradientColors = GRADIENTS[topicHash % GRADIENTS.length];

    // Generate a reasonable comparison percentage based on the score
    const userPercentile = Math.max(1, Math.min(99, Math.floor(percentage * 0.92 + (Math.random() * 5))));

    // Select AI feedback based on score
    let aiMessage = "You are getting stronger in this topic 💪";
    if (percentage >= 85) {
        aiMessage = "You are close to mastery! 🚀";
    } else if (percentage < 50) {
        aiMessage = "Consistency is key, keep pushing! ✨";
    }


    return (
        <View style={styles.container}>
            <LinearGradient
                colors={gradientColors as [string, string, ...string[]]}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                style={StyleSheet.absoluteFill}
            />

            {/* Background elements for depth */}
            <View style={[styles.circle, { top: -200, right: -200, opacity: 0.15 }]} />
            <View style={[styles.circle, { bottom: -100, left: -250, opacity: 0.1, width: 800, height: 800, borderRadius: 400 }]} />

            <View style={styles.inner}>
                {/* Logo Section */}
                <View style={styles.logoRow}>
                    <View style={styles.logoWrapper}>
                        <Image
                            source={require('../assets/images/icon.png')}
                            style={styles.logo}
                            resizeMode="contain"
                        />
                    </View>
                </View>

                {/* Content Section */}
                <View style={styles.content}>
                    <View style={styles.badgeContainer}>
                        <LinearGradient
                            colors={['rgba(255,255,255,0.1)', 'rgba(255,255,255,0.05)']}
                            style={styles.aiBadge}
                        >
                            <Text style={styles.aiBadgeText}>Generated by Skeeme AI</Text>
                        </LinearGradient>
                    </View>

                    <Text style={styles.topicText} numberOfLines={2}>{topic}</Text>

                    <View style={styles.scoreOuter}>
                        {/* Glowy Arcs around the score */}
                        <View style={styles.arcLeft} />
                        <View style={styles.arcRight} />

                        <View style={styles.scoreInner}>
                            <Text style={styles.mainScore}>{percentage}%</Text>
                        </View>

                        {/* Comparison Pill with Glow */}
                        <View style={styles.comparisonPill}>
                            <LinearGradient
                                colors={['#22d3ee', '#0ea5e9']}
                                start={{ x: 0, y: 0 }}
                                end={{ x: 1, y: 0 }}
                                style={styles.pillGradient}
                            >
                                <Text style={styles.comparisonText}>
                                    Better than {userPercentile}% of AI quiz participants!
                                </Text>
                            </LinearGradient>
                        </View>
                    </View>

                    <View style={styles.mainQuoteBox}>
                        <Text style={styles.quoteText}>✨ {aiMessage}</Text>
                    </View>

                    {/* Performance Insights Section */}
                    <View style={styles.insightsRow}>
                        <View style={styles.insightCard}>
                            <Text style={styles.insightLabel}>STRENGTH</Text>
                            <Text style={styles.insightValue}>{strength || 'Fast Learner'}</Text>
                        </View>
                        <View style={styles.insightCard}>
                            <Text style={styles.insightLabel}>FOCUS AREA</Text>
                            <Text style={styles.insightValue}>{focusArea || 'Key Concepts'}</Text>
                        </View>
                    </View>

                </View>

                {/* Footer Section */}
                <View style={styles.footer}>
                    <View style={styles.footerTop}>
                        <Text style={styles.availableText}>Available on iOS & Android</Text>
                        <View style={styles.storeIcons}>
                            <AppleIcon width={18} height={18} color="white" />
                            <GoogleIcon width={18} height={18} color="white" />
                        </View>
                    </View>
                    <View style={styles.footerBottomPill}>
                        <Text style={styles.footerUrl}>Master your studies with Skeeme</Text>
                    </View>
                </View>
            </View>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        width: 1080,
        height: 1080,
        backgroundColor: '#4f46e5',
        overflow: 'hidden',
    } as ViewStyle,
    inner: {
        flex: 1,
        paddingHorizontal: 60,
        paddingVertical: 60,
        justifyContent: 'space-between',
        alignItems: 'center',
    } as ViewStyle,
    circle: {
        position: 'absolute',
        width: 700,
        height: 700,
        borderRadius: 350,
        backgroundColor: 'rgba(255, 255, 255, 1)',
    } as ViewStyle,
    logoRow: {
        width: '100%',
        alignItems: 'center',
    } as ViewStyle,
    logoWrapper: {
        width: 140,
        height: 140,
        backgroundColor: 'rgba(0, 0, 0, 0.4)', // Darker logo container like reference
        borderRadius: 35,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    } as ViewStyle,
    logo: {
        width: '100%',
        height: '100%',
    } as ImageStyle,
    content: {
        width: '100%',
        alignItems: 'center',
        flex: 1,
    } as ViewStyle,
    badgeContainer: {
        marginTop: 40,
        marginBottom: 20,
    } as ViewStyle,
    aiBadge: {
        paddingHorizontal: 24,
        paddingVertical: 8,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    } as ViewStyle,
    aiBadgeText: {
        color: 'white',
        fontSize: 20,
        fontWeight: '700',
    } as TextStyle,
    topicText: {
        fontSize: 56,
        fontWeight: '900',
        color: 'white',
        textAlign: 'center',
        lineHeight: 70,
        marginBottom: 30,
    } as TextStyle,
    scoreOuter: {
        width: 600,
        height: 380,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    } as ViewStyle,
    scoreInner: {
        zIndex: 2,
    } as ViewStyle,
    mainScore: {
        fontSize: 260,
        fontWeight: '900',
        color: 'white',
        letterSpacing: -8,
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: { width: 0, height: 10 },
        textShadowRadius: 20,
    } as TextStyle,
    arcLeft: {
        position: 'absolute',
        left: 0,
        top: 20,
        width: 30,
        height: 340,
        borderLeftWidth: 10,
        borderTopWidth: 2,
        borderBottomWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        borderTopLeftRadius: 100,
        borderBottomLeftRadius: 100,
    } as ViewStyle,
    arcRight: {
        position: 'absolute',
        right: 0,
        top: 20,
        width: 30,
        height: 340,
        borderRightWidth: 10,
        borderTopWidth: 2,
        borderBottomWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
        borderTopRightRadius: 100,
        borderBottomRightRadius: 100,
    } as ViewStyle,
    comparisonPill: {
        position: 'absolute',
        bottom: 10,
        zIndex: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    } as ViewStyle,
    pillGradient: {
        paddingHorizontal: 30,
        paddingVertical: 12,
        borderRadius: 25,
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.5)',
    } as ViewStyle,
    comparisonText: {
        fontSize: 24,
        fontWeight: '800',
        color: 'white',
    } as TextStyle,
    mainQuoteBox: {
        width: '100%',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        paddingVertical: 20,
        paddingHorizontal: 30,
        borderRadius: 25,
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        marginBottom: 40,
        alignItems: 'center',
    } as ViewStyle,
    quoteText: {
        fontSize: 32,
        fontWeight: '800',
        color: 'white',
    } as TextStyle,
    footer: {
        width: '100%',
        alignItems: 'center',
    } as ViewStyle,
    footerTop: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
        gap: 12,
    } as ViewStyle,
    availableText: {
        fontSize: 22,
        fontWeight: '700',
        color: 'rgba(255, 255, 255, 0.8)',
    } as TextStyle,
    storeIcons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    } as ViewStyle,
    storeIcon: {
        opacity: 0.9,
    } as TextStyle,
    footerBottomPill: {
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        paddingHorizontal: 40,
        paddingVertical: 15,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    } as ViewStyle,
    footerUrl: {
        fontSize: 32,
        fontWeight: '900',
        color: '#fff',
        letterSpacing: 0.5,
    } as TextStyle,
    insightsRow: {
        flexDirection: 'row',
        width: '100%',
        gap: 20,
        marginBottom: 30,
    } as ViewStyle,
    insightCard: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        padding: 24,
        borderRadius: 25,
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    } as ViewStyle,
    insightLabel: {
        fontSize: 18,
        fontWeight: '900',
        color: 'rgba(255, 255, 255, 0.6)',
        letterSpacing: 2,
        marginBottom: 8,
    } as TextStyle,
    insightValue: {
        fontSize: 32,
        fontWeight: '800',
        color: 'white',
    } as TextStyle,
});
