export const generateQuizHTML = (quizTitle: string, score: number, questions: any[]) => {
    return `
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 20px; color: #1e293b; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #A1C4FD; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 28px; font-weight: 900; color: #0f172a; margin: 0 0 10px 0; }
        .score-bubble { display: inline-block; background: #A1C4FD; color: white; padding: 8px 16px; border-radius: 20px; font-weight: bold; font-size: 18px; margin-top: 10px; }
        .question-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 20px; page-break-inside: avoid; }
        .q-header { display: flex; justify-content: space-between; margin-bottom: 12px; align-items: center; }
        .q-num { font-size: 14px; font-weight: bold; color: #A1C4FD; text-transform: uppercase; letter-spacing: 1px; }
        .q-status { font-size: 12px; font-weight: bold; padding: 4px 8px; border-radius: 12px; }
        .correct { background: #dcfce7; color: #166534; }
        .incorrect { background: #fee2e2; color: #991b1b; }
        .q-text { font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 15px; }
        .answer-box { background: white; border: 1px solid #cbd5e1; border-radius: 8px; padding: 12px; margin-top: 15px; }
        .explanation { margin-top: 15px; font-size: 14px; color: #475569; background: #f0fdf4; padding: 12px; border-radius: 8px; border-left: 4px solid #A1C4FD; }
        .footer { text-align: center; font-size: 12px; color: #94a3b8; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
        
        /* MathJax adjustments */
        .MathJax { font-size: 1.1em !important; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">${quizTitle}</h1>
        <div class="score-bubble">Score: ${Math.round(score)}%</div>
    </div>

    <div class="questions">
        ${questions.map((q, index) => {
            const isTheory = q.type === 'essay' || q.type === 'theory' || q.question_type === 'essay';
            const questionText = q.question || q.question_text || 'No text detected';
            const isCorrect = q.is_correct !== undefined ? q.is_correct : (isTheory ? q.user_answer : q.user_answer === q.correct_answer);
            
            let answerHtml = '';
            
            if (isTheory) {
                answerHtml = `
                    <div class="answer-box">
                        <div style="font-size: 12px; font-weight: bold; color: #64748b; margin-bottom: 5px; text-transform: uppercase;">Model Answer</div>
                        <div>${q.correct_answer}</div>
                    </div>
                `;
            } else {
                answerHtml = `
                    <div class="answer-box">
                        <div style="font-size: 12px; font-weight: bold; color: #64748b; margin-bottom: 5px; text-transform: uppercase;">Your Answer</div>
                        <div style="font-weight: ${isCorrect ? 'bold' : 'normal'}; color: ${isCorrect ? '#166534' : '#991b1b'}">${q.user_answer || 'Skipped'}</div>
                        
                        ${!isCorrect ? `
                            <div style="margin-top: 10px; font-size: 12px; font-weight: bold; color: #64748b; margin-bottom: 5px; text-transform: uppercase;">Correct Answer</div>
                            <div style="font-weight: bold; color: #166534;">${q.correct_answer}</div>
                        ` : ''}
                    </div>
                `;
            }

            return `
            <div class="question-card">
                <div class="q-header">
                    <span class="q-num">Question ${index + 1}</span>
                    <span class="q-status ${isCorrect ? 'correct' : 'incorrect'}">
                        ${isCorrect ? 'Correct' : 'Incorrect'}
                    </span>
                </div>
                <div class="q-text">${questionText}</div>
                ${answerHtml}
                ${q.explanation ? `
                    <div class="explanation">
                        <strong>Explanation:</strong><br/>${q.explanation}
                    </div>
                ` : ''}
            </div>
            `;
        }).join('')}
    </div>

    <div class="footer">
        Generated by <strong>Skeeme</strong> &mdash; AI Study Assistant<br>
        <a href="https://skeeme.com/students" style="color: #A1C4FD; text-decoration: none; font-weight: bold;">Download the app &rarr; skeeme.com/students</a>
    </div>
</body>
</html>
    `;
};

export const generateScanHTML = (results: any[]) => {
    return `
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 20px; color: #1e293b; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #A1C4FD; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 28px; font-weight: 900; color: #0f172a; margin: 0 0 5px 0; }
        .subtitle { font-size: 14px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
        .question-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 20px; page-break-inside: avoid; }
        .q-header { display: flex; justify-content: space-between; margin-bottom: 12px; align-items: center; }
        .q-num { font-size: 14px; font-weight: bold; color: #A1C4FD; text-transform: uppercase; letter-spacing: 1px; }
        .q-text { font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 15px; background: white; padding: 12px; border-radius: 8px; border: 1px solid #cbd5e1; }
        .steps { margin-bottom: 15px; padding-left: 15px; }
        .step-title { font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: bold; margin-bottom: 8px; }
        .step-item { font-size: 14px; margin-bottom: 6px; }
        .solution-box { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 15px; margin-top: 15px; border-left: 4px solid #A1C4FD; }
        .footer { text-align: center; font-size: 12px; color: #94a3b8; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">Scan & Solve Results</h1>
        <div class="subtitle">Detailed Step-by-Step Breakdown</div>
    </div>

    <div class="questions">
        ${results.map((item, index) => `
            <div class="question-card">
                <div class="q-header">
                    <span class="q-num">Question ${index + 1}</span>
                    <span style="font-size: 10px; font-weight: bold; padding: 3px 8px; border-radius: 10px; text-transform: uppercase; letter-spacing: 1px; ${item.type === 'theory' ? 'background: #dbeafe; color: #1d4ed8;' : 'background: #d1fae5; color: #059669;'}">${item.type === 'theory' ? 'Theory' : 'Calculation'}</span>
                </div>
                
                <div class="q-text">${item.question || 'No text detected'}</div>
                
                ${item.type !== 'theory' ? `
                    ${item.steps && item.steps.length > 0 ? `
                        <div class="steps">
                            <div class="step-title">Solution Steps</div>
                            ${item.steps.map((step: string, sIdx: number) => `
                                <div class="step-item">${sIdx + 1}. ${step}</div>
                            `).join('')}
                        </div>
                    ` : ''}
                    
                    <div class="solution-box">
                        <div style="font-size: 12px; font-weight: bold; color: #166534; margin-bottom: 5px; text-transform: uppercase;">Final Answer</div>
                        <div style="font-weight: bold; color: #0f172a; font-size: 16px;">${item.solution}</div>
                    </div>
                ` : `
                    ${item.explanation ? `
                        <div style="margin-bottom: 15px; padding: 15px; background: #eff6ff; border-left: 4px solid #3b82f6; border-radius: 8px;">
                            <div style="font-size: 12px; font-weight: bold; color: #1d4ed8; margin-bottom: 8px; text-transform: uppercase;">Explanation</div>
                            <div style="font-size: 14px; color: #1e293b; white-space: pre-line; line-height: 1.7;">${item.explanation}</div>
                        </div>
                    ` : ''}
                    ${item.summary ? `
                        <div style="background: #dbeafe; border: 1px solid #93c5fd; border-radius: 8px; padding: 12px;">
                            <div style="font-size: 12px; font-weight: bold; color: #1d4ed8; margin-bottom: 5px; text-transform: uppercase;">Key Takeaway</div>
                            <div style="font-weight: bold; color: #0f172a; font-size: 15px;">${item.summary}</div>
                        </div>
                    ` : ''}
                `}
            </div>
        `).join('')}
    </div>

    <div class="footer">
        Generated by <strong>Skeeme</strong> &mdash; AI Study Assistant<br>
        <a href="https://skeeme.com/students" style="color: #A1C4FD; text-decoration: none; font-weight: bold;">Download the app &rarr; skeeme.com/students</a>
    </div>
</body>
</html>
    `;
};
